name: Audit
on:
  push:
    branches: [main]
  pull_request:
    branches: all 

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build
      run: go build -v ./...
    - name: Lint
      run: go vet 
    - name: Run tests
      run: go test 
